name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r software/requirements.txt
        pip install pytest
        
    - name: Run basic tests
      run: |
        # Create test data directory if it doesn't exist
        mkdir -p software/tests/test_data/
        # Add commands to download test images if needed
        python -m pytest software/tests/